sitepur/cart/urls.py
from django.urls import path
from . import views
from .views import CartView, AddToCartView, DeleteFromCartView, ChangeQtyView

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/',
         AddToCartView.as_view(),
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.DeleteFromCartView.as_view(),
         name='cart_remove'),
    path('change-qty/<int:product_id>/',
         views.ChangeQtyView.as_view(),
         name='cart_change'),
]

sitepur/catalog/urls.py
from django.urls import path
from . import views


app_name = 'catalog'

urlpatterns = [
    path('', views.CatalogHome.as_view(), name='catalog_home'),
    path('sizes/', views.Sizes, name='sizes'),
    path("filter/", views.FilterCatalogView, name="filter1"),
    path("<slug:category_slug>/filter/", views.FilterCatalogView, name="filter"),
    path("search/", views.Search.as_view(), name="search"),
    path('<slug:category_slug>/', views.CatalogHome.as_view(), name='catalog_home_by_category'),
    path('<slug:category_slug>/<slug:slug>', views.ShoesDetailView.as_view(), name='shoes-detail')
]

sitepur/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
]

sitepur/sitepur/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls')),
    path('catalog/', include(('catalog.urls', 'products'), namespace='products')),
    path('user/', include('user.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitepur/main/views.py
from django.shortcuts import render
from catalog.models import Customer, Cart


def index(request):
    # if request.user.is_authenticated:
    #     customer = Customer.objects.get(user=request.user)
    #     cart = Cart.objects.get(owner=customer)
    #
    # if request.user.is_authenticated:
    #     return render(request, 'main/index.html', {'cart': cart})
    # else:
        return render(request, 'main/index.html')

def about(request):
    # if request.user.is_authenticated:
    #     customer = Customer.objects.get(user=request.user)
    #     cart = Cart.objects.get(owner=customer)

    # if request.user.is_authenticated:
    #     return render(request, 'main/about.html', {'cart': cart})
    # else:
    return render(request, 'main/about.html')

sitepur/main/templates/main/about.html
{% extends 'main/layout.html' %}

{% block title %}Про нас{% endblock %}

{% block content %}
        <nav aria-label="breadcrumb" class="breadcrumps" id="crumps">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Связаться с нами</li>
          </ol>
        </nav>
    <div class="container border border-info p-5">
        <h1 class="text-center">Контактная информация</h1>
        <div>
            <ul>
                <li class="contact-phone"><a href="tel:+7 (495) 544-57-70">+7 (495) 544-57-70</a></li>
                <li class="contact-phone"><a href="tel:+7 (800) 775-28-34">+7 (800) 775-28-34</a></li>
            </ul>
            <p class="text-center text-secondary">Ежедневно с 9:00 до 22:00 по Московскому времени</p>
        </div>

        <div class="text-center contact-email">
            Интересующие вас вопросы Вы можете написать нам на почту
            <p class="contact-phone"><a href="mailto:store@brandshop.ru">store@brandshop.ru</a></p>
        </div>
    </div>
{% endblock %}

sitepur/main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="container features">
        <p>В данном интернет-магазине можно купить брендовые вещи</p>
        <a href="{% url 'products:catalog_home' %}" class="btn btn-primary btn-lg">Перейти к каталогу</a>
    </div>
{% endblock %}

sitepur/main/templates/main/layout.html
{% load static %}
<!doctype html>
<html lang="ru"> <!--установка языка текста на странице-->
<head>
    <meta charset="UTF-8"> <!--установка кодировки на странице-->
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title> <!--заголовок страницы-->
</head>
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main/slick/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'main/slick/slick-theme.css' %}"/>
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
</head>
<body>
    <header class="header">
        <div class="container text">
            <div class="nav">
                <a href="{% url 'products:catalog_home' %}">
                    <img src="{% static 'main/img/logo.png' %}" alt="" class="logoimg">
                </a>
                <ul class="topmenu">
                    <li><a href="{% url 'products:catalog_home' %}">Все товары</a></li>
                    <li class="menu-item"><a href="/catalog/obuv/" class="submenu-link">Обувь</a>
                    </li>
                    <li class="menu-item"><a href="/catalog/odezhda/" class="submenu-link">Одежда</a>
                    </li>
                </ul>
                <form class="search" action="{% url 'products:search' %}" method="get">
                    <div class="search">
                        <div class="input-group">
                          <div class="form-outline">
                            <input type="search" id="form1" name="search" class="form-control search" />
                          </div>
                          <button type="submit" class="btn btn-success">
                            <i class="fas fa-search"></i>
                          </button>
                        </div>
                    </div>
                </form>
                <button class="topmenu-open">
                    <img src="{% static 'main/img/hamburger.svg' %}" alt="Open menu">
                </button>
            </div>
            </div>
    </header>
    <main>
        <div class="sidebar">
            {% if not request.get_full_path == "/cart/" %}
                <a href="{% url 'cart:cart_detail' %}" title="Корзина" class="basket_a"><i class="fas fa-shopping-basket basket">
                </i></br>Корзина <span class="badge badge-pill badge-danger">{{ cart.products.count }}</span></a>
            {% endif %}
            {% if not request.user.is_authenticated %}
                <a href="{% url 'login' %}" title="Войти или зарегистрироваться"><i class="fas fa-sign-in-alt"></i></br>Вход</a>
            {% endif %}
            <a href="{% url 'about' %}" title="Контакты"><i class="fas fa-address-book"></i></br>Контакты</a>
            {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}" title="Выход из аккаунта"><i class="fas fa-sign-out-alt"></i></br>Выход</a>
            {% endif %}
        </div>
        {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert" style="text-align: center; margin-left: 10vh;">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="text-align: center; margin-left: 10vh;">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer" id="section-footer">
        <div class="container">
            <div class="footer__content">
                <div class="footer__content-logo">
                    <div class="header__logo-small"></div>
                    <div class="header__logo-big"></div>
                    <h3 class="text-center">Интернет-магазин <br> брендовых товаров</h3>
                </div>

                <div class="footer__content-adress">
                    <ul>
                        <li>Warehouse Society, 234</li>
                        <li>Bahagia Ave Street PRBW 29281</li>
                    </ul>
                </div>

                <div class="footer__content-mail">
                    <ul>
                        <li><a href="mailto:info@warehouse.project">info@warehouse.project</a></li>
                        <li><a href="tel:1-232-3434">1-232-3434 (Main)</a></li>
                    </ul>
                </div>

                <div class="footer__content-rights">
                    <ul>
                        <li>© Интернет-магазин брендовых товаров™, 2022. All rights reserved.</li>
                        <li>Регистрационный номер компании: 21479524.</li>
                    </ul>
                </div>
            </div>

            <div class="footer__links">
                <h3>Социальные сети</h3>
                <div class="footer__links-media">
                    <div class="footer__link">
                        <img src="{% static 'main/img/inst.svg' %}" alt="instagram" class="footer__link-img">
                    </div>
                    <div class="footer__link">
                        <img src="{% static 'main/img/twitter.svg' %}" alt="twitter" class="footer__link-img">
                    </div>
                    <div class="footer__link">
                        <img src="{% static 'main/img/facebook.svg' %}" alt="facebook" class="footer__link-img">
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://maps.api.2gis.ru/2.0/loader.js?pkg=full"></script>
    <script type="text/javascript" src="{% static 'main/js/main.js' %}"></script>
    <script src="{% static 'main/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'main/slick/slick.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/js/script.js' %}"></script>
    <script src="{% static 'main/js/bootstrap.min.js' %}"></script>
</body>
</html>