sitepur/cart/urls.py
from django.urls import path
from . import views
from .views import CartView, AddToCartView, DeleteFromCartView, ChangeQtyView

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/',
         AddToCartView.as_view(),
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.DeleteFromCartView.as_view(),
         name='cart_remove'),
    path('change-qty/<int:product_id>/',
         views.ChangeQtyView.as_view(),
         name='cart_change'),
]

sitepur/catalog/urls.py
from django.urls import path
from . import views


app_name = 'catalog'

urlpatterns = [
    path('', views.CatalogHome.as_view(), name='catalog_home'),
    path('sizes/', views.Sizes, name='sizes'),
    path("filter/", views.FilterCatalogView, name="filter1"),
    path("<slug:category_slug>/filter/", views.FilterCatalogView, name="filter"),
    path("search/", views.Search.as_view(), name="search"),
    path('<slug:category_slug>/', views.CatalogHome.as_view(), name='catalog_home_by_category'),
    path('<slug:category_slug>/<slug:slug>', views.ShoesDetailView.as_view(), name='shoes-detail')
]

sitepur/sitepur/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls')),
    path('catalog/', include(('catalog.urls', 'products'), namespace='products')),
    path('user/', include('user.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitepur/catalog/models.py
from django.db import models
from django.urls import reverse
from filer.fields.image import FilerImageField
from slugify import slugify
from django.contrib.auth import get_user_model
from user.models import Customer

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

User = get_user_model()

class Category(models.Model):
    name = models.CharField("Категория", unique=True, max_length = 50, db_index=True)
    slug = models.SlugField(max_length=50, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:catalog_home_by_category', args=[self.slug])

class Gender(models.Model):
    name = models.CharField("Пол", max_length=20, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Пол'
        verbose_name_plural = 'Пол'


class Subcategory(models.Model):
    name = models.CharField("Подкатегория", max_length=20, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'

class Brand(models.Model):
    name = models.CharField("Бренд", max_length=20, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'

class Articles(models.Model):
    img = models.ImageField(upload_to='sneakers_logos')
    img_thumbnail = ImageSpecField(source='img',
                                      processors=[ResizeToFill(1000, 950)],
                                      format='JPEG',
                                      options={'quality': 60})

    title = models.CharField('Название', max_length=50, db_index=True)
    slug = models.SlugField(max_length=50, db_index=True, unique=True)
    price = models.DecimalField('Цена', max_digits=10, decimal_places=2)
    description = models.TextField('Описание вещи')
    available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, verbose_name="Категория", related_name="products", on_delete=models.CASCADE)
    gender = models.ForeignKey(Gender, verbose_name="Пол", on_delete=models.SET_NULL, null=True)
    subcategory = models.ForeignKey(Subcategory, verbose_name="Подкатегория", on_delete=models.SET_NULL, null=True)
    brand = models.ForeignKey(Brand, verbose_name="Бренд", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Articles, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        return reverse('catalog:shoes-detail', args=[self.id, self.slug])


class CartProduct(models.Model):
    user = models.ForeignKey(Customer, verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey("Cart", verbose_name='Корзина', on_delete=models.CASCADE)
    product = models.ForeignKey(Articles, verbose_name='Товар', on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {}".format(self.product.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.product.price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey(Customer, null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_products')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)



class ArticlesImage(models.Model):
    post = models.ForeignKey(Articles, default=None, on_delete=models.CASCADE)
    img_detail = models.ImageField('Фотографии модели', upload_to='sneakers_img')

    def __str__(self):
        return self.post.title

    class Meta:
        verbose_name = 'Фотография модели'
        verbose_name_plural = 'Фотографии модели кроссовок'

class Size(models.Model):
    post = models.ForeignKey(Articles, default=None, on_delete=models.CASCADE)
    size = models.CharField('Размер', max_length=10)

    def __str__(self):
        return self.post.title

    class Meta:
        verbose_name = 'Размер модели'
        verbose_name_plural = 'Размеры моделей'

class Reviews(models.Model):
    article = models.ForeignKey(Articles, on_delete=models.CASCADE, verbose_name='Отзыв', blank = True, null = True, related_name='comments_articles')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор отзыва', blank=True, null=True)
    create_date = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    text = models.TextField(verbose_name='Текст отзыва')
    img_detail = models.ImageField('Фотография модели', upload_to='reviews_img')

sitepur/catalog/forms.py
from catalog.models import Reviews
from django.forms import ModelForm, Textarea, ImageField
from django.utils.safestring import mark_safe


class ReviewForm(ModelForm):
    img_detail = ImageField()
    class Meta:
        model = Reviews
        fields = ['text', 'img_detail']
        widgets = {
            "text": Textarea(attrs={
            'rows': 5,
            'class': 'form-control',
            'placeholder': 'Текст комментария'
        }),
        }

sitepur/catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Articles, ArticlesImage, Gender, Subcategory, Brand, Category, Size, Customer, Cart
from .mixins import CartMixin
from django.views.generic import DetailView, View
from django.db.models import Q
from cart.forms import CartAddProductForm
from .forms import ReviewForm
from django.views.generic.edit import FormMixin
from django.http import Http404



class CatalogHome(CartMixin, View):

    def get(self, request, category_slug=None, *args, **kwargs):
        category = None
        categories = Category.objects.all()
        catalog = Articles.objects.filter(available=True)
        subcategory = Subcategory.objects.all()
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            catalog = Articles.objects.filter(category=category, available=True)
            subcategory = Subcategory.objects.filter(articles__category=category).distinct()
        print(category_slug)
        gen = Gender.objects.all()
        brand = Brand.objects.all()
        context = {'catalog': catalog, 'category': category, 'categories': categories,
                                                         'genders': gen, 'subcategory': subcategory,
                                                         'brand': brand, 'cart': self.cart}
        return render(request, 'catalog/catalog_home.html', context)

class ShoesDetailView(CartMixin, FormMixin, DetailView):
    model = Articles
    template_name = 'catalog/details_view.html'
    context_object_name = 'article'
    form_class = ReviewForm

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ShoesDetailView, self).get_context_data(**kwargs)
        # Add extra context from another model
        context['articleimg'] = ArticlesImage.objects.filter(post=self.object)
        context['size'] = Size.objects.filter(post=self.object)
        context['cart_product_form'] = CartAddProductForm()
        context['cart'] = self.cart
        context['form'] = self.get_form()
        return context


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.article = self.get_object()
        self.object.author = self.request.user
        self.object.img = form.instance
        self.object.save()
        return super(ShoesDetailView, self).form_valid(form)

    def form_invalid(self, form):
        self.object = form.save(commit=False)
        self.object.article = self.get_object()
        self.object.author = self.request.user
        self.object.img = form.instance
        self.object.save()
        return super(ShoesDetailView, self).form_invalid(form)




def FilterCatalogView(request, category_slug=None):
    if request.user.is_authenticated:
        customer = Customer.objects.filter(user=request.user)
        cart = Cart.objects.filter(owner=customer)
    category = None
    categories = Category.objects.all()
    catalog = Articles.objects.filter(available=True)
    subcategory = Subcategory.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        catalog = Articles.objects.filter(category=category, available=True)
        subcategory = Subcategory.objects.filter(articles__category=category).distinct()
    if "sort" in request.GET:
        if request.GET.getlist("sort") == ['max']:
            catalog = catalog.order_by('-price')
        elif request.GET.getlist("sort") == ['min']:
            catalog = catalog.order_by('price')
        elif request.GET.getlist("sort") == ['new']:
            catalog = catalog.order_by('title')
        elif request.GET.getlist("sort") == ['latest']:
            catalog = catalog.order_by('-title')
        else:
            pass
    if "gender" in request.GET:
        catalog = catalog.filter(gender__name__in=request.GET.getlist("gender"), available=True)
    if "subcategory" in request.GET:
        catalog = catalog.filter(subcategory__name__in=request.GET.getlist("subcategory"), available=True)
    if "brand" in request.GET:
        catalog = catalog.filter(brand__name__in=request.GET.getlist("brand"), available=True)

    gen = Gender.objects.all()
    brand = Brand.objects.all()
    if request.user.is_authenticated:
        return render(request, 'catalog/catalog_home.html',
                  {'catalog': catalog, 'category': category, 'categories': categories,
                   'genders': gen, 'subcategory': subcategory, 'brand': brand, 'cart': cart})
    else:
        return render(request, 'catalog/catalog_home.html',
                      {'catalog': catalog, 'category': category, 'categories': categories,
                       'genders': gen, 'subcategory': subcategory, 'brand': brand})


class Search(CartMixin, View):
    def get(self, request, *args, **kwargs):
        catalog = Articles.objects.filter(title__icontains=request.GET.get("search"), available=True)
        gen = Gender.objects.all()
        brand = Brand.objects.all()
        subcategory = Subcategory.objects.all()
        return render(request, 'catalog/catalog_home.html',
                      {'catalog': catalog, 'genders': gen, 'subcategory': subcategory, 'brand': brand, 'cart': self.cart})


def Sizes(request):
    return render(request, 'catalog/sizes.html')

sitepur/catalog/templates/catalog/catalog_home.html
{% extends 'main/layout.html' %}

{% block title %}Все товары{% endblock %}

{% block content %}
        <div class="container">
            <div class="row">
                <nav aria-label="breadcrumb" class="breadcrumbs">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'products:catalog_home' %}">Каталог</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ category.name }}</li>
                  </ol>
                </nav>
            </div>
            <div class="row items">
                <div class="col-3 justify-content-center filters">
                    <div class="filters_set">
                        {% if request.path == '/catalog/filter/' or request.path == '/catalog/' or request.path == '/catalog/search/' or request.path == '/catalog/sort/' %}
                        <form action="{% url 'products:filter1' %}" method="get">
                        {% else %}
                        <form action="/catalog/{{ category.slug }}/filter/" method="get">
                        {% endif %}
                            <div class="accordeonWrapper type_1">
                                <div class="elemAccordeon">
                                    <div class="descElem">
                                        <select class="select_send_ajax sort-select" name="sort">
                                        <optgroup label="По популярности">
                                            <option>Более популярные</option>
                                       </optgroup>
                                       <optgroup label="По цене">
                                                <option value="max">По убыванию</option>
                                                <option value="min">По возрастанию</option>
                                       </optgroup>
                                       <optgroup label="По новизне">
                                                <option value="new">Сначала новые</option>
                                                <option value="latest">Сначала старые</option>
                                       </optgroup>
                                    </select>
                                    </div>
                                </div>

                                <div class="elemAccordeon">
                                    <div class="headingElem">ПОЛ</div>
                                    <div class="descElem">
                                        {% for el in genders %}
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" name="gender" value="{{ el }}" id="flexCheckDefault{% cycle 1 2 3 %}">
                                                <label class="form-check-label55" for="flexCheckDefault{% cycle 1 2 3 %}">
                                                    {{ el.name }}
                                                </label>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="elemAccordeon">
                                    <div class="headingElem">ПОДКАТЕГОРИЯ</div>
                                    <div class="descElem">
                                        {% for el in subcategory %}
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" name="subcategory" value="{{ el }}" id="flexCheckDefault{% cycle 4 5 6 7 8 9 %}">
                                                <label class="form-check-label55" for="flexCheckDefault{% cycle 4 5 6 7 8 9 %}">
                                                    {{ el.name }}
                                                </label>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="elemAccordeon">
                                    <div class="headingElem">БРЕНД</div>
                                    <div class="descElem">
                                        {% for el in brand %}
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" name="brand" value="{{ el }}" id="flexCheckDefault{% cycle 10 11 12 13 14 15 %}">
                                                <label class="form-check-label55" for="flexCheckDefault{% cycle 10 11 12 13 14 15 %}">
                                                    {{ el.name }}
                                                </label>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-outline-primary" id="btn-filter">ПОКАЗАТЬ</button>
                        </form>
                    </div>
                </div>
        {% if catalog %}
                <div class="col-9 colItems">
            {% for el in catalog %}
                    <div class="card text-white bg-dark mb-3 item">
                      <a href="{{ el.get_absolute_url }}">
                          <img class="card-img-top" src="{{ el.img_thumbnail.url }}" alt="Card image cap">
                      </a>
                      <div class="card-body">
                          <h3 id="hthing">{{ el.title }}</h3>
                          <span class="align-top">{{ el.price }} &#8381</span>
                          <div style="clear: both"></div>
                          <span class="bthing">
                            <a href="{{ el.get_absolute_url }}" class="btn btn-info btn-sm">Купить</a>
                          </span>
                      </div>
                    </div>
            {% endfor %}
                </div>
        {% else %}
            <p>На данный момент товары отсутствуют</p>
        {% endif %}
                </div>
            </div>
{% endblock %}

sitepur/catalog/templates/catalog/details_view.html
{% extends 'main/layout.html' %}

{% block title %}Товар {{ article.title }}{% endblock %}
{% load static %}
{% block content %}
    <div class="features">
        <nav aria-label="breadcrumb" class="breadcrumps" id="crumps">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{% url 'products:catalog_home' %}">Каталог</a></li>
              <li class="breadcrumb-item"><a href="/catalog/{{ article.category.slug }}/">{{ article.category.name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ article.title }}</li>
          </ol>
        </nav>

        <div class="container-fluid detail_product">
            <div class="row justify-content-right">
                <div class="col-sm-6 detailtablecol1">
                    <div class="single-item">
                        {% if articleimg %}
                            {% for el in articleimg %}
                                <div class="slick_item"><img src="{{ el.img_detail.url }}" width="100%" height="400px"></div>
                            {% endfor %}
                        {% else %}
                            <div class="slick_item"><img src="{% static 'main/img/no-img.png' %}" width="100%" height="400px"></div>
                        {% endif %}

                    </div>
                </div>
                <div class="col-sm-3 detailtablecol2">
                    {{ article.title }}
                    <div class="row">
                        <div class="col-sm">
                            <h6>Выберите размер</h6>
                        </div>
                        <div class="col-sm">
                            <a href="{% url 'products:sizes' %}" id="acoldetail"><h6>Таблица размеров <i class="fa fa-info" aria-hidden="true"></i></h6></a>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-sm">
                            {% for el in size %}
                                <input type="radio" class="btn-check" name="options" value="{{ el.size }}" onclick="check" id="option{{ forloop.counter }}" autocomplete="off">
                                <label class="btn btn-secondary sizeButt" for="option{{ forloop.counter }}">{{ el.size }}</label>
                                {% if forloop.counter|divisibleby:4 %}
                                   <br>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <input class="form-control" id = "size" type="text" readonly>
                    <div class="row">
                        <div class="col">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'cart:cart_add' article.id %}" class="btn btn-warning">Добавить в корзину</a>
                            {% else %}
                                <p>Зарегистрируйтесь, чтобы добавить товар</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="col-sm-2 detailtablecol3">
                    {{ article.price }} &#8381
                </div>
            </div>
            <div id="accordion" style="width: 90%">
                <div class="card mt-4">
                    <div class="card-header" id="headingOne">
                      <h5 class="mb-0">
                        <button class="btn btn-light" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                          Описание
                        </button>
                          <button class="btn btn-light" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                          Характеристики
                          </button>
                      </h5>
                    </div>
                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                      <div class="card-body">
                        {{ article.description }}
                      </div>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                        <div class="card-body">
                        Test
                        </div>
                    </div>
                </div>
        </div>
            <div class="comments mt-5">
                    <h3 class="">Отзывы ({{ article.comments_articles.all.count }})</h3>
                    <hr color="white">
                    <h3 class="">Добавить отзыв</h3>
                    <form action="" id="add_form" method="post" class="comments">
                    {% csrf_token %}
                    {{ form }}
                    <button form="add_form" type="submit" class="btn btn-info mt-2" style="width: 100px">Добавить
                    </button>
                    </form>
                    <ul>
                    {% for item in article.comments_articles.all %}
                    <li>
                    <div class="alert alert-primary comment-card">
                    {{ item.create_date }}<br>
                    {{ item.author }}<br>
                    {{ item.text }}
                    </div>
                    </li>
                    {% endfor %}
                    </ul>
                </div>
    </div>
{% endblock %}