sitepur/cart/urls.py
from django.urls import path
from . import views
from .views import CartView, AddToCartView, DeleteFromCartView, ChangeQtyView

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart_detail'),
    path('add/<int:product_id>/',
         AddToCartView.as_view(),
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.DeleteFromCartView.as_view(),
         name='cart_remove'),
    path('change-qty/<int:product_id>/',
         views.ChangeQtyView.as_view(),
         name='cart_change'),
]

sitepur/catalog/urls.py
from django.urls import path
from . import views


app_name = 'catalog'

urlpatterns = [
    path('', views.CatalogHome.as_view(), name='catalog_home'),
    path('sizes/', views.Sizes, name='sizes'),
    path("filter/", views.FilterCatalogView, name="filter1"),
    path("<slug:category_slug>/filter/", views.FilterCatalogView, name="filter"),
    path("search/", views.Search.as_view(), name="search"),
    path('<slug:category_slug>/', views.CatalogHome.as_view(), name='catalog_home_by_category'),
    path('<slug:category_slug>/<slug:slug>', views.ShoesDetailView.as_view(), name='shoes-detail')
]

sitepur/sitepur/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls')),
    path('catalog/', include(('catalog.urls', 'products'), namespace='products')),
    path('user/', include('user.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitepur/cart/models.py
from django.db import models

sitepur/cart/forms.py
from django import forms
from catalog.models import Articles


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        label = 'Количество',
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput)

sitepur/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.views import View
from catalog.mixins import CartMixin
from django.http import HttpResponseRedirect
from catalog.models import Articles, Cart, Customer, CartProduct
from catalog.utils import recalc_cart
from .forms import CartAddProductForm


class CartView(CartMixin, View):
    def get(self, request, *args, **kwargs):
        context = {
            'cart': self.cart,
        }
        return render(request, 'cart/detail.html', context)


class AddToCartView(CartMixin, View):
    def get(self, request, product_id, *args, **kwargs):
        product = Articles.objects.get(id=product_id)
        cart_product, created = CartProduct.objects.get_or_create(
            user=self.cart.owner, cart=self.cart, product=product
        )
        if created:
            self.cart.products.add(cart_product)
        recalc_cart(self.cart)
        return HttpResponseRedirect('/cart/')


class DeleteFromCartView(CartMixin, View):
    def get(self, request, product_id, *args, **kwargs):
        product = Articles.objects.get(id=product_id)
        cart_product = CartProduct.objects.get(
            user=self.cart.owner, cart=self.cart, product=product
        )
        self.cart.products.remove(cart_product)
        cart_product.delete()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Товар успешно удален")
        return HttpResponseRedirect('/cart/')


class ChangeQtyView(CartMixin, View):

    def post(self, request, product_id, *args, **kwargs):
        product = Articles.objects.get(id=product_id)
        cart_product = CartProduct.objects.get(
            user=self.cart.owner, cart=self.cart, product=product
        )
        qty = int(request.POST.get('qty'))
        cart_product.qty = qty
        cart_product.save()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Кол-во успешно изменено")
        return HttpResponseRedirect('/cart/')



def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Articles, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

sitepur/cart/templates/cart/detail.html
{% extends 'main/layout.html' %}
{% block title %}Корзина покупок{% endblock %}

{% block content %}
    <div class="container bucket">
        <h1>Корзина покупок {% if not cart.products.count %}пуста{% endif %}</h1>
        {% if cart.products.count %}
		<div class="table-responsive">
        <table class="table align-middle table-secondary table-sm cart">
            <thead>
                <tr>
                    <th>Картинка</th>
                    <th>Товар</th>
                    <th>Удалить</th>
                    <th>Цена за шт</th>
                    <th>Размер</th>
                    <th>Кол-во</th>
                    <th>Общая стоимость</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart.products.all %}
                    {% with product=item.product %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{{ product.img_thumbnail.url }}" class="ProductImg">
                                </a>
                            </td>
                            <td>{{ product.title }}</td>
                            <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
                            <td>
                                {{ product.price }}
                            </td>
                            <td>
                                123
                            </td>
                            <td>
                                <form action="{% url 'cart:cart_change' product.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="number" name="qty" class="form-control" min="1" max="5" value="{{ item.qty }}" style="width: 65px;">
                                    <br>
                                    <input type="submit" class="btn btn-outline-secondary btn-sm" value="Изменить кол-во">
                                </form>
                            </td>
                            <td>{{ item.final_price }}</td>
                        </tr>

            {% endwith %}
            {% endfor %}
            </tbody>
            <tr>
                <td style="font-weight: bold; font-size: 18px;">Всего</td>
                <td colspan="4"></td>
                <td style="font-weight: bold; font-size: 18px;">{{ cart.total_products }}</td>
                <td style="font-weight: bold; font-size: 18px;">{{ cart.final_price }}</td>
            </tr>
        </table>
		</div>
        <p class="text-right">
            <a href="{% url 'products:catalog_home' %}" class="btn btn-info">В магазин</a>
            <a href="{% url 'checkout' %}" class="btn btn-info">Оформить заказ</a>
        </p>
        {% endif %}
    </div>
{% endblock %}